/** @format */

import {attribute, table, autoGeneratedHashKey, rangeKey} from '@aws/dynamodb-data-mapper-annotations'

@table(process.env.DYNAMODB_TABLE || '')
export class Project {
  @autoGeneratedHashKey()
  id: string

  @attribute()
  name: string

  @attribute()
  description: string

  @attribute()
  startDate: string

  @attribute()
  endDate: string

  @attribute()
  state: string

  @attribute()
  promoter: [string]

  @attribute()
  location: any
}
