service: sorace-sendMessage # NOTE: update this with your service name
plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-central-1
  environment:
    DYNAMODB_TABLE: soraceUserTable
    DYNAMODB_TABLE: soraceUserTable
  iamRoleStatements: # permissions for all of your functions can be set here
    - Effect: Allow
      Action: # Gives permission to DynamoDB tables in a specific region
        - logs:*
      Resource: "*"
functions:
  addRole:
    handler: src/handler.sendMessage
    memorySize: 128
