service: sorace-recieveMessage # NOTE: update this with your service name
plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-central-1
  environment:
    DYNAMODB_TABLE: Project-ybc4qcwxkfd7xeqhvlvmhd6boq-dev
  iamRoleStatements: # permissions for all of your functions can be set here
    - Effect: Allow
      Action: # Gives permission to DynamoDB tables in a specific region
        - cognito-idp:*
        - logs:*
        - dynamodb:*
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/*"
functions:
  addRole:
    handler: src/handler.recieveMessage
    memorySize: 128
